package web

import (
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"gorm.io/gorm"

	"scrutineer/internal/db"
)

// findingReport renders a single finding as a downloadable markdown document,
// scoped to just that one vulnerability rather than the whole scan or repo.
// Triage often focuses on one finding at a time (e.g. handling a High before a
// Low from the same scan, #299), so this lets a recipient get exactly that
// finding's report. The per-finding section reuses writeReportFinding from
// repo_report.go so a finding-scoped report reads identically to the same
// finding inside a scan or repo report.
func (s *Server) findingReport(w http.ResponseWriter, r *http.Request) {
	var f db.Finding
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		http.NotFound(w, r)
		return
	}
	if err := s.DB.First(&f, id).Error; err != nil {
		http.NotFound(w, r)
		return
	}
	// Scan and Repository loads are best-effort: a finding always carries a
	// denormalised RepositoryID/Commit, so a missing scan or repo row only
	// costs us the header's repo link, not the finding body.
	var scan db.Scan
	s.DB.First(&scan, f.ScanID)
	var repo db.Repository
	s.DB.First(&repo, f.RepositoryID)

	body := renderFindingReport(s.DB, &f, &scan, &repo)

	w.Header().Set("Content-Type", "text/markdown; charset=utf-8")
	w.Header().Set("Content-Disposition", `attachment; filename="`+findingReportFilename(&repo, &f)+`"`)
	_, _ = w.Write([]byte(body))
}

func findingReportFilename(repo *db.Repository, f *db.Finding) string {
	return fmt.Sprintf("scrutineer-%s-finding-%d-%s.md",
		sanitiseFilename(repo.Name),
		f.ID,
		time.Now().UTC().Format("20060102"))
}

func renderFindingReport(gdb *gorm.DB, f *db.Finding, scan *db.Scan, repo *db.Repository) string {
	return renderFindingReportAt(gdb, f, scan, repo, time.Now())
}

func renderFindingReportAt(
	gdb *gorm.DB,
	f *db.Finding,
	scan *db.Scan,
	repo *db.Repository,
	generatedAt time.Time,
) string {
	var b strings.Builder
	writeFindingReportHeader(&b, f, repo, generatedAt)
	writeReportFinding(&b, gdb, *f, scan, audienceAnalyst)
	return b.String()
}

// writeFindingReportHeader mirrors the scan report's header (writeScanReportHeader)
// so a finding-scoped report opens the same way: a title line, the source repo
// link, and the generation stamp. The title is "{repo} — finding #N" rather than
// the finding title itself because writeReportFinding already emits a
// "### Finding #N: {title}" section below, matching scan_report.go's layout.
func writeFindingReportHeader(
	b *strings.Builder,
	f *db.Finding,
	repo *db.Repository,
	generatedAt time.Time,
) {
	repoName := firstNonEmpty(repo.FullName, repo.Name, repo.URL)
	fmt.Fprintf(b, "# %s — finding #%d\n\n", firstNonEmpty(repoName, "scrutineer"), f.ID)
	if repo.URL != "" {
		fmt.Fprintf(b, "From [%s](%s).\n\n", repoName, repo.URL)
	} else if repoName != "" {
		fmt.Fprintf(b, "From %s.\n\n", repoName)
	}
	fmt.Fprintf(b, "Generated by [scrutineer](https://github.com/alpha-omega-security/scrutineer) at %s UTC.\n\n",
		generatedAt.UTC().Format("2006-01-02 15:04"))
	b.WriteString("---\n\n")
}
