package web

import (
	"fmt"
	"regexp"
	"strings"
)

// fencedBlock is the standard three-backtick code fence with an optional
// info string on the opening line. Indented (four-space) code blocks are
// not extracted: the audit and verify skills are told to paste the
// reproduction verbatim into a fenced block, so an indented block is
// almost always output text or a quoted excerpt rather than the runnable
// artefact.
var fencedBlock = regexp.MustCompile("(?s)```[ \t]*([a-zA-Z0-9_+.-]*)[^\n]*\n(.*?)```")

// probeExt maps a fence info string (already lowercased) to the
// filename its body is written as under poc/. Only explicit shell script
// fences become run.sh; console, shell-session, text, and unmarked fences
// are transcripts and may contain prompts or observed output.
var probeExt = map[string]string{
	"":             "transcript.txt",
	"sh":           "run.sh",
	"bash":         "run.sh",
	"shell":        "run.sh",
	"zsh":          "run.sh",
	"console":      "session.txt",
	"shellsession": "session.txt",
	"text":         "transcript.txt",
	"python":       "probe.py",
	"python3":      "probe.py",
	"py":           "probe.py",
	"ruby":         "probe.rb",
	"rb":           "probe.rb",
	"javascript":   "probe.js",
	"js":           "probe.js",
	"typescript":   "probe.ts",
	"ts":           "probe.ts",
	"go":           "probe.go",
	"golang":       "probe.go",
	"rust":         "probe.rs",
	"rs":           "probe.rs",
	"swift":        "probe.swift",
	"c":            "probe.c",
	"cpp":          "probe.cpp",
	"c++":          "probe.cpp",
	"java":         "Probe.java",
	"php":          "probe.php",
	"perl":         "probe.pl",
	"ocaml":        "probe.ml",
	"json":         "input.json",
	"xml":          "input.xml",
	"yaml":         "input.yaml",
	"yml":          "input.yaml",
	"http":         "request.http",
}

// probeRunner maps a probe filename to the shell line that runs it, for
// the generated run.sh when the validation prose supplied a language
// probe but no shell driver. Filenames not listed here (transcripts,
// input.*, .go, .rs, .c, .cpp, .java, request.http) have no obvious
// one-line runner; the generated run.sh points at README.md instead.
var probeRunner = map[string]string{
	"probe.py":  "exec python3 probe.py \"$@\"",
	"probe.rb":  "exec ruby probe.rb \"$@\"",
	"probe.js":  "exec node probe.js \"$@\"",
	"probe.ts":  "exec npx ts-node probe.ts \"$@\"",
	"probe.php": "exec php probe.php \"$@\"",
	"probe.pl":  "exec perl probe.pl \"$@\"",
}

const runShMode = 0o755

// bundlePoC turns a finding's Validation prose into a poc/ directory for
// the disclosure bundle. Each fenced code block becomes a file named for
// its fence language; the full prose lands in poc/README.md so the
// recipient keeps the surrounding context (expected output, fingerprint,
// caveats). When the prose supplied a language probe but no shell driver,
// a minimal run.sh is generated that invokes the first probe. Returns nil
// when the prose has no fenced blocks: report.md already carries the
// validation text, and a poc/ with only a README would add nothing
// runnable.
func bundlePoC(validation string) []bundleEntry {
	blocks := fencedBlock.FindAllStringSubmatch(validation, -1)
	if len(blocks) == 0 {
		return nil
	}

	seen := map[string]int{}
	var entries []bundleEntry
	var firstProbe string
	haveRunSh := false

	for _, m := range blocks {
		lang := strings.ToLower(strings.TrimSpace(m[1]))
		body := m[2]
		if strings.TrimSpace(body) == "" {
			continue
		}
		if !strings.HasSuffix(body, "\n") {
			body += "\n"
		}
		name, ok := probeExt[lang]
		if !ok {
			name = "probe." + lang
		}
		executable := name == "run.sh"
		seen[name]++
		if n := seen[name]; n > 1 {
			name = suffixBeforeExt(name, n)
		}
		var mode int64
		if executable {
			haveRunSh = true
			mode = runShMode
		}
		if firstProbe == "" && strings.HasPrefix(name, "probe.") {
			firstProbe = name
		}
		entries = append(entries, bundleEntry{Name: "poc/" + name, Data: []byte(body), Mode: mode})
	}
	if len(entries) == 0 {
		return nil
	}

	if !haveRunSh {
		entries = append([]bundleEntry{{
			Name: "poc/run.sh",
			Data: []byte(generatedRunSh(firstProbe)),
			Mode: runShMode,
		}}, entries...)
	}

	entries = append(entries, bundleEntry{
		Name: "poc/README.md",
		Data: []byte(pocReadme(validation)),
	})
	return entries
}

// suffixBeforeExt inserts -n before the final dot: probe.py, 2 -> probe-2.py.
// A name with no dot gets the suffix appended.
func suffixBeforeExt(name string, n int) string {
	i := strings.LastIndexByte(name, '.')
	if i <= 0 {
		return fmt.Sprintf("%s-%d", name, n)
	}
	return fmt.Sprintf("%s-%d%s", name[:i], n, name[i:])
}

func generatedRunSh(firstProbe string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by scrutineer from the finding's Validation field.\n")
	b.WriteString("# See README.md in this directory for expected output and context.\n")
	b.WriteString("cd \"$(dirname \"$0\")\"\n")
	if run, ok := probeRunner[firstProbe]; ok {
		b.WriteString(run + "\n")
	} else {
		b.WriteString("echo 'No shell driver in the original reproduction; see README.md and probe files.' >&2\n")
		b.WriteString("exit 2\n")
	}
	return b.String()
}

func pocReadme(validation string) string {
	var b strings.Builder
	b.WriteString("# Reproduction\n\n")
	b.WriteString("This directory is the finding's Validation step materialised as files. ")
	b.WriteString("Fenced code blocks from the text below have been written out alongside ")
	b.WriteString("this README; run.sh is either the shell block from the reproduction or ")
	b.WriteString("a generated stub that invokes the first probe.\n\n")
	b.WriteString("## Validation (verbatim)\n\n")
	b.WriteString(strings.TrimSpace(validation))
	b.WriteString("\n")
	return b.String()
}
