package web

import (
	"encoding/json"
	"fmt"
	"net/http"
	"sort"
	"strconv"
	"strings"
	"time"

	"gorm.io/gorm"

	"scrutineer/internal/db"
)

// scanReport renders a single scan's results as a downloadable markdown
// document. For findings-kind scans the format mirrors the per-finding
// sections produced by repo_report.go so a scan-scoped report and a
// repo-scoped one read the same way. For other output kinds (maintainers,
// packages, freeform SBOMs, etc.) the JSON is walked and rendered as
// markdown tables when the shape allows, falling back to a fenced JSON
// block only for shapes we can't tabulate (non-object top level, no
// scalar fields, no arrays of objects).
func (s *Server) scanReport(w http.ResponseWriter, r *http.Request) {
	var scan db.Scan
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		http.NotFound(w, r)
		return
	}
	if err := s.DB.Preload("Repository").First(&scan, id).Error; err != nil {
		http.NotFound(w, r)
		return
	}

	skill := loadScanReportSkill(s.DB, &scan)

	var body string
	if isDiscloseScanReport(&scan, skill) {
		body = renderSavedDisclosureScanReport(s.DB, &scan)
		if body == "" {
			http.Error(w, "no saved disclosure draft to export", http.StatusNotFound)
			return
		}
	} else {
		body = renderScanReport(s.DB, &scan, skill)
	}

	w.Header().Set("Content-Type", "text/markdown; charset=utf-8")
	w.Header().Set("Content-Disposition", `attachment; filename="`+scanReportFilename(&scan)+`"`)
	_, _ = w.Write([]byte(body))
}

func scanReportFilename(scan *db.Scan) string {
	return fmt.Sprintf("scrutineer-%s-scan-%d-%s-%s.md",
		sanitiseFilename(scan.Repository.Name),
		scan.ID,
		sanitiseFilename(firstNonEmpty(scan.SkillName, scan.Kind, "scan")),
		time.Now().UTC().Format("20060102"))
}

func loadScanReportSkill(gdb *gorm.DB, scan *db.Scan) *db.Skill {
	if scan.SkillID == nil {
		return nil
	}
	var skill db.Skill
	if err := gdb.Select("id", "output_kind").First(&skill, *scan.SkillID).Error; err != nil {
		return nil
	}
	return &skill
}

func hasExportableScanReport(gdb *gorm.DB, scan *db.Scan, skill *db.Skill) bool {
	if isDiscloseScanReport(scan, skill) {
		return renderSavedDisclosureScanReport(gdb, scan) != ""
	}
	return scan.HasExportableReport()
}

func renderScanReport(gdb *gorm.DB, scan *db.Scan, skill *db.Skill) string {
	kind := ""
	if skill != nil {
		kind = skill.OutputKind
	}
	var b strings.Builder
	writeScanReportHeader(&b, scan)
	writeScanReportMetadata(&b, scan, skill)
	switch kind {
	case "findings", "advisory_audit":
		// advisory_audit persists ordinary Finding rows alongside its
		// per-advisory verdicts, so its report.md keeps the same curated
		// per-finding prose as a findings-kind scan.
		writeScanReportFindings(&b, gdb, scan)
	default:
		writeScanReportFreeform(&b, scan, kind)
	}
	return b.String()
}

func isDiscloseScanReport(scan *db.Scan, skill *db.Skill) bool {
	if skill != nil {
		return skill.OutputKind == "disclose"
	}
	return scan.SkillName == discloseSkillName
}

func renderSavedDisclosureScanReport(gdb *gorm.DB, scan *db.Scan) string {
	if gdb == nil || scan.FindingID == nil {
		return ""
	}
	var finding db.Finding
	if err := gdb.Select("id", "title", "disclosure_draft").First(&finding, *scan.FindingID).Error; err != nil {
		return ""
	}
	return renderFindingDisclosureMarkdown(&finding)
}

func writeScanReportHeader(b *strings.Builder, scan *db.Scan) {
	title := firstNonEmpty(scan.SkillName, scan.Kind, "scan")
	fmt.Fprintf(b, "# %s — scan #%d\n\n", title, scan.ID)
	repoName := firstNonEmpty(scan.Repository.FullName, scan.Repository.Name, scan.Repository.URL)
	if scan.Repository.URL != "" {
		fmt.Fprintf(b, "From [%s](%s).\n\n", repoName, scan.Repository.URL)
	} else if repoName != "" {
		fmt.Fprintf(b, "From %s.\n\n", repoName)
	}
	fmt.Fprintf(b, "Generated by [scrutineer](https://github.com/alpha-omega-security/scrutineer) at %s UTC.\n\n",
		time.Now().UTC().Format("2006-01-02 15:04"))
	fmt.Fprintf(b, "---\n\n")
}

func writeScanReportMetadata(b *strings.Builder, scan *db.Scan, skill *db.Skill) {
	fmt.Fprintf(b, "## Scan metadata\n\n")
	rows := [][2]string{
		{"Scan ID", fmt.Sprintf("%d", scan.ID)},
		{"Repository", firstNonEmpty(scan.Repository.FullName, scan.Repository.Name)},
		{"Skill", scan.SkillName},
		{"Status", string(scan.Status)},
		{"Model", scan.Model},
	}
	if skill != nil && skill.OutputKind != "" {
		rows = append(rows, [2]string{"Output kind", skill.OutputKind})
	}
	if scan.Commit != "" {
		rows = append(rows, [2]string{"Commit", "`" + shortCommit(scan.Commit) + "`"})
	}
	if scan.Ref != "" {
		rows = append(rows, [2]string{"Ref", scan.Ref})
	}
	if scan.StartedAt != nil {
		rows = append(rows, [2]string{"Started", scan.StartedAt.UTC().Format(time.RFC3339)})
	}
	if scan.FinishedAt != nil {
		rows = append(rows, [2]string{"Finished", scan.FinishedAt.UTC().Format(time.RFC3339)})
		if scan.StartedAt != nil {
			rows = append(rows, [2]string{"Duration", scan.FinishedAt.Sub(*scan.StartedAt).Round(time.Second).String()})
		}
	}
	if scan.Turns > 0 {
		rows = append(rows, [2]string{"Turns", fmt.Sprintf("%d", scan.Turns)})
	}
	if scan.CostUSD > 0 {
		rows = append(rows, [2]string{"Cost", fmt.Sprintf("$%.4f", scan.CostUSD)})
	}
	if scan.FindingsCount > 0 {
		rows = append(rows, [2]string{"Findings reported", fmt.Sprintf("%d", scan.FindingsCount)})
	}

	fmt.Fprintf(b, "| Field | Value |\n|---|---|\n")
	for _, r := range rows {
		if r[1] == "" {
			continue
		}
		fmt.Fprintf(b, "| %s | %s |\n", r[0], r[1])
	}
	b.WriteString("\n")

	if strings.TrimSpace(scan.Error) != "" {
		fmt.Fprintf(b, "### Error\n\n```\n%s\n```\n\n", strings.TrimSpace(scan.Error))
	}
}

func writeScanReportFindings(b *strings.Builder, gdb *gorm.DB, scan *db.Scan) {
	// Findings whose last_seen_scan_id matches this scan are what the
	// scan reported on its most recent run; ScanID matches when the
	// scan first introduced the finding. We OR them so a scan that
	// re-observed an existing finding (the common case after the first
	// run on a repo) still surfaces it here. Edge case: a finding first
	// seen in this scan but re-observed in a later scan will appear here
	// because scan_id matches, even though its location/locations now
	// reflect HEAD at the later scan — the DB doesn't snapshot per-scan
	// state, so report data for older scans is inherently a today-view.
	// scan_show.html's Preload("Findings") uses only the implicit ScanID
	// FK and undercounts the same way; worth a separate issue.
	var findings []db.Finding
	gdb.Where("last_seen_scan_id = ? OR scan_id = ?", scan.ID, scan.ID).
		Order(severityOrder).Order("id").Find(&findings)
	fmt.Fprintf(b, "## Findings\n\n")
	if len(findings) == 0 {
		fmt.Fprintf(b, "No findings recorded by this scan.\n\n")
		return
	}

	fmt.Fprintf(b, "%d finding(s).\n\n", len(findings))
	fmt.Fprintf(b, "| # | Severity | Status | Title | Location |\n|---|---|---|---|---|\n")
	for _, f := range findings {
		fmt.Fprintf(b, "| %d | %s | %s | %s | `%s` |\n",
			f.ID, f.Severity, f.Status, escapeMD(f.Title), f.Location)
	}
	b.WriteString("\n")

	// Reuse the per-finding prose renderer from repo_report.go so a scan
	// report and a repo report describe the same finding the same way.
	for _, f := range findings {
		writeReportFinding(b, gdb, f, scan, audienceAnalyst)
	}
}

// writeScanReportFreeform renders a scan's report.json as the best
// markdown the shape allows: top-level scalar keys become a metadata
// table, top-level arrays of objects each become their own section with
// a table whose columns are the most common scalar keys. CycloneDX SBOMs
// are recognised by their bomFormat marker and given a tuned heading.
// Anything we can't make sense of (non-object top level, or no
// tabulatable arrays and no scalars) falls back to a fenced JSON block —
// accuracy never sacrificed for prettiness.
func writeScanReportFreeform(b *strings.Builder, scan *db.Scan, kind string) {
	raw := strings.TrimSpace(scan.Report)
	if raw == "" {
		fmt.Fprintf(b, "## Report\n\nNo report produced.\n\n")
		return
	}

	var top map[string]any
	if err := json.Unmarshal([]byte(raw), &top); err != nil {
		// Top isn't a JSON object — could be a bare array, plain text, or
		// malformed JSON. We don't try to guess; we ship it as-is.
		writeScanReportJSONBlock(b, raw, kind)
		return
	}

	fmt.Fprintf(b, "## %s\n\n", freeformHeading(top, kind))

	scalars, arrays := classifyTopLevel(top)
	wroteAnything := writeScalarTable(b, top, scalars)
	for _, k := range arrays {
		items, _ := top[k].([]any)
		writeArraySection(b, k, items)
		wroteAnything = true
	}

	// If we ended up writing nothing of substance (e.g. the top-level
	// object is all nested objects we couldn't summarise), fall back so
	// the user still gets the data.
	if !wroteAnything {
		writeScanReportJSONBlock(b, raw, kind)
	}
}

func writeScanReportJSONBlock(b *strings.Builder, raw, kind string) {
	label := "Raw report"
	if kind != "" {
		label = fmt.Sprintf("Raw report (%s)", kind)
	}
	fmt.Fprintf(b, "## %s\n\n", label)
	// prettyJSON (from jsontree.go) re-indents valid JSON and passes
	// non-JSON through unchanged, so this stays readable whether the
	// skill emitted pretty output, compact output, or something else.
	fmt.Fprintf(b, "```json\n%s\n```\n\n", prettyJSON(raw))
}

func freeformHeading(top map[string]any, kind string) string {
	if format, _ := top["bomFormat"].(string); format == "CycloneDX" {
		spec, _ := top["specVersion"].(string)
		if spec != "" {
			return fmt.Sprintf("SBOM (CycloneDX %s)", spec)
		}
		return "SBOM (CycloneDX)"
	}
	if kind != "" {
		return "Report (" + kind + ")"
	}
	return "Report"
}

// classifyTopLevel sorts an object's keys into scalar-shaped (single-row
// metadata) and array-of-objects (their own section). Arrays of scalars
// and nested objects ride along in the scalar bucket since they fit a
// single cell when stringified.
func classifyTopLevel(top map[string]any) (scalars, arrays []string) {
	keys := make([]string, 0, len(top))
	for k := range top {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		if arr, ok := top[k].([]any); ok && len(arr) > 0 {
			if _, ok := arr[0].(map[string]any); ok {
				arrays = append(arrays, k)
				continue
			}
		}
		scalars = append(scalars, k)
	}
	return scalars, arrays
}

func writeScalarTable(b *strings.Builder, top map[string]any, keys []string) bool {
	rows := make([][2]string, 0, len(keys))
	for _, k := range keys {
		v := freeformCellString(top[k])
		if v == "" {
			continue
		}
		rows = append(rows, [2]string{k, v})
	}
	if len(rows) == 0 {
		return false
	}
	fmt.Fprintf(b, "| Field | Value |\n|---|---|\n")
	for _, r := range rows {
		fmt.Fprintf(b, "| %s | %s |\n", escapeMD(r[0]), escapeMD(r[1]))
	}
	b.WriteString("\n")
	return true
}

func writeArraySection(b *strings.Builder, key string, items []any) {
	fmt.Fprintf(b, "### %s (%d)\n\n", key, len(items))
	if len(items) == 0 {
		b.WriteString("None.\n\n")
		return
	}
	cols := pickFreeformColumns(items)
	if len(cols) == 0 {
		// Nothing tabulatable — emit the array as a JSON block so the
		// data isn't lost.
		buf, _ := json.MarshalIndent(items, "", "  ")
		fmt.Fprintf(b, "```json\n%s\n```\n\n", string(buf))
		return
	}
	b.WriteString("|")
	for _, c := range cols {
		fmt.Fprintf(b, " %s |", escapeMD(c))
	}
	b.WriteString("\n|")
	for range cols {
		b.WriteString("---|")
	}
	b.WriteString("\n")
	for _, item := range items {
		m, ok := item.(map[string]any)
		if !ok {
			continue
		}
		b.WriteString("|")
		for _, c := range cols {
			fmt.Fprintf(b, " %s |", escapeMD(freeformCellString(m[c])))
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")
}

// pickFreeformColumns walks up to 50 items, counts which scalar-shaped
// keys are commonly present, and returns up to 6 of them. Preferred
// names (name, version, license, ...) come first when present so SBOMs,
// package lists, and advisory lists all render with the columns a reader
// would expect.
func pickFreeformColumns(items []any) []string {
	const sampleSize = 50
	const maxCols = 6

	counts := map[string]int{}
	seen := 0
	for i, item := range items {
		if i >= sampleSize {
			break
		}
		m, ok := item.(map[string]any)
		if !ok {
			continue
		}
		seen++
		for k, v := range m {
			if isFreeformCellValue(v) {
				counts[k]++
			}
		}
	}
	if seen == 0 {
		return nil
	}

	preferred := []string{
		"name", "version", "type", "ecosystem",
		"license", "licenses", "purl",
		"severity", "cwe", "cve", "cvss", "rating",
		"title", "summary", "description",
		"location", "url", "id", "login", "email",
	}
	used := map[string]bool{}
	out := make([]string, 0, maxCols)
	for _, k := range preferred {
		if counts[k] > 0 {
			out = append(out, k)
			used[k] = true
			if len(out) >= maxCols {
				return out
			}
		}
	}

	type kn struct {
		k string
		n int
	}
	rest := make([]kn, 0, len(counts))
	for k, n := range counts {
		if !used[k] {
			rest = append(rest, kn{k, n})
		}
	}
	sort.Slice(rest, func(i, j int) bool {
		if rest[i].n != rest[j].n {
			return rest[i].n > rest[j].n
		}
		return rest[i].k < rest[j].k
	})
	for _, r := range rest {
		if len(out) >= maxCols {
			break
		}
		out = append(out, r.k)
	}
	return out
}

// isFreeformCellValue tells writeArraySection whether a value fits in a
// single markdown table cell. Strings, numbers, booleans, and short
// lists of those (including CycloneDX-style [{id: "MIT"}]) qualify;
// arbitrary nested objects do not.
func isFreeformCellValue(v any) bool {
	const maxInlineArrayLen = 5
	switch x := v.(type) {
	case nil, bool, float64, string:
		return true
	case []any:
		if len(x) > maxInlineArrayLen {
			return false
		}
		for _, e := range x {
			switch ev := e.(type) {
			case string, float64, bool, nil:
				continue
			case map[string]any:
				if _, ok := ev["id"]; ok {
					continue
				}
				if _, ok := ev["name"]; ok {
					continue
				}
				return false
			default:
				return false
			}
		}
		return true
	default:
		return false
	}
}

// freeformCellString collapses a JSON value into a single-line string
// suitable for a markdown table cell. For leaf scalars it delegates to
// scalarString (defined in jsontree.go) so number/bool/null formatting
// stays consistent with the HTML Data tab. The cases here cover what's
// specific to markdown cells: collapsing license arrays
// (CycloneDX [{id: "MIT"}] → "MIT"), and skipping deep nested objects
// (so writeScalarTable drops their row entirely) rather than rendering
// them as a bracketed placeholder.
func freeformCellString(v any) string {
	switch x := v.(type) {
	case nil:
		return ""
	case []any:
		const cap = 3
		parts := make([]string, 0, cap)
		for _, e := range x {
			var s string
			switch ev := e.(type) {
			case map[string]any:
				if id, ok := ev["id"].(string); ok {
					s = id
				} else if name, ok := ev["name"].(string); ok {
					s = name
				}
			default:
				s = scalarString(ev)
			}
			if s != "" {
				parts = append(parts, s)
			}
			if len(parts) >= cap && len(x) > cap {
				parts = append(parts, fmt.Sprintf("(+%d more)", len(x)-cap))
				break
			}
		}
		return strings.Join(parts, ", ")
	case map[string]any:
		// Nested objects don't fit a single table cell. Surface only if
		// there's an obvious one-line representation; otherwise return
		// empty so writeScalarTable drops the row entirely.
		if name, ok := x["name"].(string); ok {
			return name
		}
		if id, ok := x["id"].(string); ok {
			return id
		}
		return ""
	default:
		return scalarString(v)
	}
}
